### PR TITLE
Automatically chdir to /vagrant on login

### PR DESCRIPTION
**Pull request by unnawut**
Issue/Task Number: N/A

# Overview

This might look silly but this has been annoying me for months. This PR automatically runs `cd /vagrant` when logging in to the VM from `vagrant ssh`.

Without it, each time I login to the VM, I need to type `cd /vag` + `tab` to not conflict with `cd /var`.

This is as energy-wasting as proof-of-work!

# Changes

- Added `cd /vagrant` to .bashrc if it does not exist

# Implementation Details

- Added a new Ansible task as `bashrc.yml`
- The file `.bashrc` already exists and we want to add `cd /vagrant` only if it doesn't exist. So we need to check using `grep` first, then add the line if `grep` produces no result.

# Usage

From your goban directory on your host machine, run `vagrant provision`. The provisioning should complete successfully and you should see the following tasks completed:

```
TASK [commons : Find `cd /vagrant` line in .bashrc] ****************************
changed: [ewallet]

TASK [commons : add `cd /vagrant` to .bashrc if it doesn't exist yet] **********
changed: [ewallet]
```

# Impact

Pull the latest commit. Run `vagrant provision` from your host machine.

### CODE REVIEW

**Comment by sirn** [comment]
Probably better to provide a default `.bashrc` as a file or template. I'll take a look at this later.

**Comment by unnawut** [comment]
There's a lot of goodies that comes with the original `.bashrc` though. Not sure if we want to maintain the file ourselves...

```bash
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
#[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    #alias grep='grep --color=auto'
    #alias fgrep='fgrep --color=auto'
    #alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
#alias ll='ls -l'
#alias la='ls -A'
#alias l='ls -CF'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi
```

**Comment by sirn** [comment]
The default `.bashrc` attempt to provides all kind of sane defaults for all terminal combination, so we can remove pretty much all of that since we provisioned the whole setup ourselves :-)

For a reference, my personal `.bashrc` looked like this before I switched to ZSH. 

* [bashrc](https://github.com/sirn/dotfiles/blob/e1623eea86a3c11e17511d7c477a6b67666a7978/etc/bashrc)
* [bash_profile](https://github.com/sirn/dotfiles/blob/e1623eea86a3c11e17511d7c477a6b67666a7978/etc/bash_profile)
* [profile](https://github.com/sirn/dotfiles/blob/e1623eea86a3c11e17511d7c477a6b67666a7978/etc/profile)

**Comment by unnawut** [comment]
Right. The next question is probably ... what should we keep as _our default_? Especially when this project is likely used by a lot more people beyond the OMG team.

I'm ok to start with the default `.bashrc` though. The colored prompt & colored `ls` is definitely useful to me.

**Comment by sirn** [comment]
I'd say something like this would be good enough defaults:

```bash
[[ $- != *i* ]] && return
[[ -s /etc/bash.bashrc ]] && source /etc/bash.bashrc
[[ -s ~/.bash_aliases ]] && source ~/.bash_aliases

shopt -s checkwinsize
shopt -s histappend
HISTCONTROL=ignoreboth
HISTSIZE=1000
HISTFILESIZE=2000

PS1="\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ "

alias ls='ls --color=auto'
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

[[ $- != *c* ]] && cd /vagrant
```

**Pull request merged**
